# Generated by Django 2.2.5 on 2022-03-22 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='prince',
            new_name='price',
        ),
    ]
